apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containers.containerPort }}