# CICD using GitHub actions

name: cicd

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deploy/**'
      - 'README.md'
      - '.idea'

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.23.0
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.0

      - name: Build
        run: go build -o go-web-app

      - name: Test
        run: go test ./...

  code-quality: # static code analysis
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2

  push:
    runs-on: ubuntu-22.04

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

  update-tag-in-helm-values-yaml:
    runs-on: ubuntu-22.04

    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' deploy/helm/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "malabatalent@gmail.com"
          git config --global user.name "Talent Malaba"
          git add deploy/helm/values.yaml
          git commit -m "Updated tag in Helm values.yaml"
          git push


